apiVersion: apps/v1
kind: Deployment
metadata:
  name: nuxt-deployment
  namespace: sample-app-for-cicd
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: nuxt-app
          image: ghcr.io/ta8i2chi8/sample-app-for-cicd:3c81ba4
          ports:
            - containerPort: 3000